public class CalculatorST {
    public static integer add(integer a, integer b) {
        return a+b;
    }
    public static integer add(integer x, integer y, integer z) {
      
     
        return x+y+z;
    }

}





// Object a =10;
// Object c = a;
// Object b = 10;
// long l = 10;
// Object objl = 10;
// String s ='10';
// Object obj ='10';
        

// System.debug(a===c);
// System.debug(a===b);
// System.debug(s==obj);
// //System.debug(a==s);
// System.debug(a==l);
// //System.debug(a===l);
// System.debug(a==objl);