public with sharing class CSVFileReadLWC {
    @AuraEnabled
    public static list<Account> csvFileRead(Id contentDocumentId){
        list<Account> accountInsertList = new list<Account>();
        if(contentDocumentId != null) {
            
            // Fetch File Data based on the basic of document id 
            ContentVersion contentVersionObj = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:contentDocumentId];
            // split the file data
            list<String> csvRecordsList = contentVersionObj.VersionData.toString().split('\n');
            system.debug('csvRecordsList===>'+csvRecordsList);

            for(Integer i = 1; i < csvRecordsList.size(); i++){
                Account accountObj = new Account();
                list<String> csvRowData = csvRecordsList[i].split(',');
                System.debug('csvRowData====> '+csvRowData);
                accountObj.Name = csvRowData[0]; // Account Name
                accountObj.AccountSource = csvRowData[1]; // Account Source
                accountObj.Rating = csvRowData[2]; // Rating
                accountObj.AccountNumber = csvRowData[3]; //Account Number               
                accountInsertList.add(accountObj);
            }

            //Madhu - Try Mapping via Custom Settinngs or Custom Metadata

            try{    
                if(!accountInsertList.isEmpty()) {
                    insert accountInsertList;
                }
            }
            catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            } 
        }
        return accountInsertList;    
    }

}